@DataShare_API_HostAddress = http://localhost:5051

### Ajouter un nouvel utilisateur
POST {{DataShare_API_HostAddress}}/api/User
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe5@example.com",
  "password": "MonSuperMotDePasse"
}
