name: Deploy MkDocs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Installer MkDocs
        run: pip install mkdocs mkdocs-material

      - name: Déployer le site
        run: mkdocs gh-deploy --force